### ISSUE TITLE
Flask app returns the following error

### ISSUE THREAD

**Issue by Cuciu** [Cuciu/Investing4.0#1]
jinja2.exceptions.TemplateSyntaxError
jinja2.exceptions.TemplateSyntaxError: expected token 'in', got '|'

Traceback (most recent call last)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\App1.0.py", line 32, in result
return render_template("result.html", result=r)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\templating.py", line 138, in render_template
ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 883, in get_template
return self._load_template(name, self.make_globals(globals))
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 857, in _load_template
template = self.loader.load(self, name, globals)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\loaders.py", line 127, in load
code = environment.compile(source, name, filename)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 638, in compile
self.handle_exception(source=source_hint)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\templates\result.html", line 40, in template
{% for key|tojson in result|tojson %}
jinja2.exceptions.TemplateSyntaxError: expected token 'in', got '|'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by Cuciu** [comment]
* Serving Flask app "App1.0" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 132-346-341
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [10/Jul/2020 10:59:27] "GET / HTTP/1.1" 200 -
('1844.30', '143.22', [1.25, 4.9, 6.15, 20.146, 22.9921], '1660.00', '119.21')
('159.00', '72.00')
127.0.0.1 - - [10/Jul/2020 10:59:39] "POST /result HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\App1.0.py", line 34, in result
    return render_template("result.html", result=r)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\templates\result.html", line 15, in top-level template code
    {{ graphdata|tojson }});
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\json\__init__.py", line 376, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\json\__init__.py", line 290, in htmlsafe_dumps
    dumps(obj, **kwargs)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python38\Lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python38\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python38\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\cuciurean\PycharmProjects\Investing-AI-1.0\Lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python38\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Undefined is not JSON serializable
127.0.0.1 - - [10/Jul/2020 10:59:39] "GET /result?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [10/Jul/2020 10:59:39] "GET /result?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Jul/2020 10:59:39] "GET /result?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Jul/2020 10:59:39] "GET /result?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [10/Jul/2020 10:59:39] "GET /result?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
